name: CI Run pytest

# This workflow allows to run pytest for multiple Python interpreters set up
# for multiple OSes.  With the setup of `tox.ini`, it complements the `pytest`
# checks locally run as defined by the Makefile.

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
#    schedule:
#    - cron: "0 0 1 * *"  # once each 1st of a month, at 00:00 UTC (cf. https://crontab.guru/)

jobs:
  test:
    strategy:
      matrix:
        # for a factorial test, an explicit selection of GitHUb runner images
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        # state of commit 0e37973 as visited on 2025-04-29 Tue
        os: ["ubuntu-24.04", "windows-latest"]
        python-version: ["3.10", "3.13"]
    runs-on: ${{ matrix.os }}

    timeout-minutes: 10  # Timeout for each job individually

    steps:
      - uses: actions/checkout@v4
        # by [2024-10-23 Wed], this version possibly will be considered "old", cf.
        # https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with PyPI
        run: pip install pytest

      - name: Run the checks by pytest
        run: |
          echo "check by pytest"
          python -m pytest -v
