name: CI Run pytest by uv

# This workflow allows to run pytest for multiple Python interpreters set up
# for multiple OSes.  With the setup of `tox.ini`, it complements the `pytest`
# checks locally run as defined by the Makefile.

on:
  push:
    branches:
      - main
      - dev
#  pull_request:
#    branches:
#      - main
#      - dev
  workflow_dispatch:
#  schedule:
#    - cron: "0 0 1 * *"  # once each 1st of a month, at 00:00 UTC (cf. https://crontab.guru/)


# derived from example of <https://github.com/astral-sh/setup-uv>:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu-24.04", "windows-latest"]
        python-version: ["3.10", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with python ${{ matrix.python-version }}
        run: |
          uv venv 
          uv pip install pytest 
          uv run --active pytest
